laravel/routes/web.php
<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect()->route('blog.index');
});

Route::get('/file', 'FileController@index')->name('file.index');
Route::delete('/file', 'FileController@destroy')->name('file.destroy');
Route::get('/file/create-update', 'FileController@create')->name('file.create');
Route::post('/file', 'FileController@store')->name('file.store');

Route::get('/image','ImageController@index')->name('image.index');
Route::get('/image/show','ImageController@show')->name('image.show');
Route::delete('/image','ImageController@destroy')->name('image.destroy');
Route::post('/image','ImageController@store')->name('image.store');

Route::resource('blog', 'BlogController')->except(['show']);
Route::get('/blog/json','BlogController@json')->name('blog.json');

laravel/app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    public $timestamps = false;
    protected $fillable = [
        'title',
        'body',
    ];

}

laravel/app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;

class BlogController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Blogs = Blog::all();
        return view('blogs.index', compact('Blogs'));
    }


    public function json()
    {
        //
        $Blogs = Blog::all();
        return response()->json($Blogs);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('blogs.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'body' => ['required'],
            'title' => ['required'],
        ]);
        Blog::create($validatedData);
        // return redirect()->route('blog.index');
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $Blog = Blog::findOrFail($id);
        return view('blogs.edit', compact('Blog'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Blog = Blog::findOrFail($id);
        $validatedData = $request->validate([
            'body' => ['required'],
            'title' => ['required'],
        ]);
        $Blog->update($validatedData);
        // return redirect()->route('blog.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Blog = Blog::findOrFail($id);
        $Blog->delete();
        // return redirect()->route('blog.index');
    }
}

laravel/resources/views/blogs/create.blade.php
@extends('layout')

@section('body')
<a href="{{route('blog.index')}}" class="button is-primary is-small">Back</a>
<hr>
<form action="{{route('blog.store')}}" method="POST">
    @csrf
    <div class="field">
        <label class="label">Title</label>
        <div class="control">
            <input class="input" type="text" name="title">
        </div>
    </div>
    <div class="field">
        <label class="label">Body</label>
        <div class="control">
            <textarea class="textarea" name="body"></textarea>

        </div>
    </div>


    <button type="submit" class="button is-link">Save</button>
</form>

@endsection

laravel/resources/views/blogs/edit.blade.php
    @extends('layout')

    @section('body')
    <a href="{{route('blog.index')}}" class="button is-primary is-small">Back</a>
    <hr>
    <form action="{{route('blog.update', $Blog->id)}}" method="POST">
        @csrf
        @method('patch')

        <div class="field">
            <label class="label">Title</label>
            <div class="control">
                <input class="input" type="text" name="title" value="{{$Blog->title}}">
            </div>
        </div>
        <div class="field">
            <label class="label">Body</label>
            <div class="control">
                <textarea class="textarea" name="body" rows="15">{{$Blog->body}}</textarea>

            </div>
        </div>


        <button type="submit" class="button is-link">Update</button>
    </form>

    @endsection

laravel/resources/views/blogs/index.blade.php
@extends('layout')

@section('body')
<a href="{{route('blog.create')}}" class="button is-primary is-small">Create</a>
<hr>
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
    <thead>
        <tr>
            <th>ID</th>
            <th>Title</th>
            <th>Body</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($Blogs as $Blog)
        <tr>
            <td>{{$Blog->id}}</td>
            <td>{{$Blog->title}}</td>
            <td>{{$Blog->body}}</td>
            <td width="150px">
                <a href="{{route('blog.edit', $Blog->id)}}" class="button is-warning is-small">Edit</a>
                <form action="{{route('blog.destroy', $Blog->id)}}" method="POST" style="display: inline;">
                    @csrf
                    @method('delete')
                    <button type="submit" class="button is-danger is-small">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach

    </tbody>
</table>
@endsection